# Generated by Django 5.0.4 on 2024-11-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_attendees_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sub_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
