# Generated by Django 5.0.4 on 2024-12-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_user_score_alter_userprofile_user_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_participation',
            field=models.BooleanField(default=False),
        ),
    ]
