# Generated by Django 5.0.4 on 2024-12-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_user_first_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='participated_events_count',
            field=models.IntegerField(default=0),
        ),
    ]
